import { colors, fonts, fontSizes } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const signupStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.ivory,
  },
  topbar: {
    backgroundColor: colors.ivory,
    paddingHorizontal: 14,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  topbarBrand: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 48,
    pointerEvents: 'none',
  },
  signinBody: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 22,
    paddingVertical: 8,
  },
  signinTitle: {
    fontFamily: fonts.serif,
    fontSize: 28,
    lineHeight: 34,
    color: colors.text,
    textAlign: 'center',
    marginBottom: 6,
  },
  signinSub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.4,
    textAlign: 'center',
    marginBottom: 16,
  },
  brandLockup: {
    alignItems: 'center',
    marginBottom: 14,
  },
  back: {
    backgroundColor: colors.cream,
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  backHidden: {
    opacity: 0,
  },
  backText: {
    color: colors.navy,
    fontSize: 18,
    fontFamily: fonts.sansRegular,
    lineHeight: 20,
  },
  progressTrack: {
    flex: 1,
    height: 4,
    backgroundColor: colors.paleBlue,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.terracotta,
    borderRadius: 2,
  },
  body: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 10,
  },
  eyebrow: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansBold,
    color: colors.navy,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  title: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.display,
    color: colors.text,
    lineHeight: fontSizes.display * 1.28,
    marginBottom: 8,
  },
  sub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.5,
    marginBottom: 20,
  },
  subAfter: {
    marginTop: 10,
    marginBottom: 0,
  },
  field: {
    marginBottom: 13,
  },
  label: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  input: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    backgroundColor: colors.cream,
  },
  inputSm: {
    flex: 1,
    paddingVertical: 11,
    paddingHorizontal: 12,
    fontSize: fontSizes.body,
  },
  inputFocused: {
    borderColor: colors.navy,
  },
  inputShake: {
    borderColor: colors.terracotta,
  },
  choiceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  choice: {
    width: '47%',
    flexGrow: 1,
    backgroundColor: colors.cream,
    borderWidth: 1.5,
    borderColor: colors.transparent,
    borderRadius: 13,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  choiceSel: {
    borderColor: colors.terracotta,
    backgroundColor: colors.cream,
    boxShadow: `0px 1px 3px ${colors.choiceShadow}`,
    elevation: 1,
  },
  choiceIcon: {
    fontSize: 24,
    marginBottom: 6,
  },
  choiceLabel: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.navy,
    textAlign: 'center',
  },
  choiceSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 3,
    lineHeight: fontSizes.caption * 1.35,
    textAlign: 'center',
  },
  kidRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
    alignItems: 'center',
  },
  remove: {
    width: 26,
    height: 26,
    backgroundColor: colors.paleBlue,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 16,
    fontFamily: fonts.sansRegular,
  },
  addRow: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansSemiBold,
    color: colors.navy,
    paddingVertical: 10,
    paddingHorizontal: 2,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.paleBlue,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 13,
    marginBottom: 14,
  },
  toggleCopy: {
    flex: 1,
  },
  toggleLabel: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  toggleSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 2,
  },
  switch: {
    width: 32,
    height: 18,
    backgroundColor: colors.paleBlue,
    borderRadius: 9,
    justifyContent: 'center',
  },
  switchOn: {
    backgroundColor: colors.switchOn,
  },
  knob: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.cream,
    boxShadow: `0px 1px 2px ${colors.knobShadow}`,
    elevation: 2,
  },
  knobOn: {
    left: 16,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  checkbox: {
    width: 20,
    height: 20,
    marginTop: 2,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 4,
    backgroundColor: colors.cream,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxOn: {
    backgroundColor: colors.rose,
    borderColor: colors.terracotta,
  },
  checkboxMark: {
    color: colors.white,
    fontSize: 12,
    fontFamily: fonts.sansBold,
    lineHeight: 14,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
  },
  connList: {
    gap: 7,
  },
  connRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 9,
    paddingHorizontal: 11,
  },
  connIcon: {
    fontSize: 17,
    width: 22,
    textAlign: 'center',
  },
  connCopy: {
    flex: 1,
    minWidth: 0,
  },
  connLabel: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  connSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 2,
  },
  connBtn: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: colors.cream,
    color: colors.navy,
  },
  connBtnOn: {
    backgroundColor: colors.sage,
    color: colors.navy,
  },
  textarea: {
    width: '100%',
    minHeight: 64,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 13,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    textAlignVertical: 'top',
    backgroundColor: colors.cream,
  },
  chipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  chip: {
    backgroundColor: colors.cream,
    borderRadius: 13,
    paddingVertical: 5,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chipText: {
    color: colors.navy,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
  },
  chipX: {
    color: colors.navy,
    opacity: 0.6,
    fontSize: fontSizes.title,
    fontFamily: fonts.sansRegular,
  },
  summaryCard: {
    backgroundColor: colors.paleBlue,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 4,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 10,
  },
  summaryRowLast: {
    borderBottomWidth: 0,
  },
  summaryKey: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  summaryVal: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
    textAlign: 'right',
    flex: 1,
  },
  footer: {
    paddingHorizontal: 18,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.cream,
  },
  skip: {
    textAlign: 'center',
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    paddingTop: 10,
    paddingBottom: 4,
    textDecorationLine: 'underline',
    textDecorationColor: colors.border,
  },
  continue: {
    width: '100%',
    backgroundColor: colors.navy,
    borderRadius: 22,
    paddingVertical: 14,
    alignItems: 'center',
  },
  continueDisabled: {
    opacity: 0.7,
  },
  continueInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  continueText: {
    color: colors.white,
    fontSize: fontSizes.header,
    fontFamily: fonts.sansSemiBold,
  },
  errorBanner: {
    marginTop: 12,
    backgroundColor: colors.blush,
    borderWidth: 1.5,
    borderColor: colors.terracotta,
    borderRadius: 11,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  errorBannerText: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.roseDeep,
    lineHeight: fontSizes.body * 1.45,
  },
});
