import { colors, fonts } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const signupStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.cream,
  },
  topbar: {
    backgroundColor: colors.rose,
    paddingHorizontal: 14,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  back: {
    backgroundColor: colors.whiteMuted,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backHidden: {
    opacity: 0,
  },
  backText: {
    color: colors.white,
    fontSize: 12,
    fontFamily: fonts.sansRegular,
    lineHeight: 14,
  },
  progressTrack: {
    flex: 1,
    height: 4,
    backgroundColor: colors.whiteTrack,
    borderRadius: 2,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.white,
    borderRadius: 2,
  },
  body: {
    flexGrow: 1,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 10,
  },
  eyebrow: {
    fontSize: 8.5,
    fontFamily: fonts.sansBold,
    color: colors.roseDark,
    textTransform: 'uppercase',
    letterSpacing: 0.09 * 8.5,
    marginBottom: 6,
  },
  title: {
    fontFamily: fonts.serif,
    fontSize: 17,
    color: colors.text,
    lineHeight: 17 * 1.32,
    marginBottom: 5,
  },
  sub: {
    fontSize: 10,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 10 * 1.55,
    marginBottom: 16,
  },
  subAfter: {
    marginTop: 10,
    marginBottom: 0,
  },
  field: {
    marginBottom: 13,
  },
  label: {
    fontSize: 8.5,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.06 * 8.5,
    marginBottom: 5,
  },
  input: {
    width: '100%',
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 13,
    fontSize: 11.5,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    backgroundColor: colors.cream,
  },
  inputSm: {
    flex: 1,
    paddingVertical: 9,
    paddingHorizontal: 11,
    fontSize: 10.5,
  },
  inputFocused: {
    borderColor: colors.rose,
  },
  inputShake: {
    borderColor: colors.rose,
  },
  choiceGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  choice: {
    width: '47%',
    flexGrow: 1,
    backgroundColor: colors.roseLight,
    borderWidth: 1.5,
    borderColor: colors.transparent,
    borderRadius: 13,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  choiceSel: {
    borderColor: colors.rose,
    backgroundColor: colors.white,
    boxShadow: `0px 2px 10px ${colors.choiceShadow}`,
    elevation: 3,
  },
  choiceIcon: {
    fontSize: 24,
    marginBottom: 6,
  },
  choiceLabel: {
    fontSize: 10,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
    textAlign: 'center',
  },
  choiceSub: {
    fontSize: 8.5,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 2,
    lineHeight: 8.5 * 1.3,
    textAlign: 'center',
  },
  kidRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
    alignItems: 'center',
  },
  remove: {
    width: 26,
    height: 26,
    backgroundColor: colors.grayLight,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeText: {
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 16,
    fontFamily: fonts.sansRegular,
  },
  addRow: {
    fontSize: 10,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
    paddingVertical: 8,
    paddingHorizontal: 2,
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: colors.grayLight,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 13,
    marginBottom: 14,
  },
  toggleCopy: {
    flex: 1,
  },
  toggleLabel: {
    fontSize: 10.5,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  toggleSub: {
    fontSize: 8.5,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  switch: {
    width: 32,
    height: 18,
    backgroundColor: colors.grayLight,
    borderRadius: 9,
    justifyContent: 'center',
  },
  switchOn: {
    backgroundColor: colors.switchOn,
  },
  knob: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.white,
    boxShadow: `0px 1px 2px ${colors.knobShadow}`,
    elevation: 2,
  },
  knobOn: {
    left: 16,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: 2,
    paddingHorizontal: 2,
  },
  checkbox: {
    width: 14,
    height: 14,
    marginTop: 2,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 3,
    backgroundColor: colors.cream,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxOn: {
    backgroundColor: colors.rose,
    borderColor: colors.rose,
  },
  checkboxMark: {
    color: colors.white,
    fontSize: 9,
    fontFamily: fonts.sansBold,
    lineHeight: 11,
  },
  checkboxLabel: {
    flex: 1,
    fontSize: 9.5,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 9.5 * 1.5,
  },
  connList: {
    gap: 7,
  },
  connRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 9,
    paddingHorizontal: 11,
  },
  connIcon: {
    fontSize: 17,
    width: 22,
    textAlign: 'center',
  },
  connCopy: {
    flex: 1,
    minWidth: 0,
  },
  connLabel: {
    fontSize: 10.5,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  connSub: {
    fontSize: 8.5,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  connBtn: {
    fontSize: 8.5,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: colors.roseLight,
    color: colors.roseDark,
  },
  connBtnOn: {
    backgroundColor: colors.tealLight,
    color: colors.teal,
  },
  textarea: {
    width: '100%',
    minHeight: 64,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 13,
    fontSize: 10.5,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    textAlignVertical: 'top',
  },
  chipList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 10,
  },
  chip: {
    backgroundColor: colors.roseLight,
    borderRadius: 13,
    paddingVertical: 5,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chipText: {
    color: colors.roseDark,
    fontSize: 9,
    fontFamily: fonts.sansMedium,
  },
  chipX: {
    color: colors.roseDark,
    opacity: 0.6,
    fontSize: 11,
    fontFamily: fonts.sansRegular,
  },
  summaryCard: {
    backgroundColor: colors.grayLight,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 4,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 10,
  },
  summaryRowLast: {
    borderBottomWidth: 0,
  },
  summaryKey: {
    fontSize: 10,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  summaryVal: {
    fontSize: 10,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
    textAlign: 'right',
    flex: 1,
  },
  footer: {
    paddingHorizontal: 18,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.cream,
  },
  skip: {
    textAlign: 'center',
    fontSize: 9.5,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    paddingTop: 8,
    paddingBottom: 2,
    textDecorationLine: 'underline',
    textDecorationColor: colors.border,
  },
  continue: {
    width: '100%',
    backgroundColor: colors.rose,
    borderRadius: 20,
    paddingVertical: 12,
    alignItems: 'center',
  },
  continueText: {
    color: colors.white,
    fontSize: 11.5,
    fontFamily: fonts.sansSemiBold,
  },
});
