import { colors, fonts, fontSizes, radii, space } from '@/constants/theme';
import { Platform, StyleSheet } from 'react-native';

/**
 * colour_class → pastel wash.
 * school stored as blue historically → sage; medical as teal → paleBlue (appointments).
 * Ambiguous: activity → blush (personal/fun); returns/home both used rose — returns now paleBlue (practical), home blush.
 */
export const iconBg = {
  rose: colors.blush,
  amber: colors.paleBlue,
  teal: colors.sage,
  blue: colors.sage,
  purple: colors.blush,
  green: colors.paleBlue,
};

const cardLift = {
  boxShadow: `0px 1px 2px ${colors.cardShadow}`,
  elevation: 1,
} as const;

export const appStyles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.ivory,
  },
  headerWrap: {
    backgroundColor: colors.ivory,
  },
  header: {
    backgroundColor: colors.ivory,
    paddingHorizontal: space.gutter,
    paddingTop: 4,
    overflow: 'visible',
  },
  greeting: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansLight,
    color: colors.navy,
    opacity: 0.7,
    marginBottom: 1,
  },
  appName: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.display,
    letterSpacing: -0.4,
    color: colors.terracotta,
  },
  mlBar: {
    backgroundColor: colors.cream,
    marginTop: 8,
    marginBottom: 12,
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mlStat: {
    fontSize: fontSizes.label,
    color: colors.headerStat,
    fontFamily: fonts.sansRegular,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: colors.cream,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 4,
  },
  tabIconWrap: {
    width: 44,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIconWrapActive: {
    backgroundColor: colors.ivory,
  },
  tabActive: {},
  tabLabel: {
    marginTop: 2,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansMedium,
    color: colors.textHint,
    letterSpacing: 0.085,
  },
  tabLabelActive: {
    color: colors.terracotta,
  },
  screen: {
    flexGrow: 1,
    backgroundColor: colors.ivory,
    paddingBottom: 20,
  },
  screenTitle: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.display,
    lineHeight: Math.round(fontSizes.display * 1.12),
    letterSpacing: -0.5,
    color: colors.navy,
    paddingHorizontal: space.gutter,
    paddingTop: 6,
    paddingBottom: 10,
  },
  slabel: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansMedium,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.64,
    paddingTop: space.sectionTop,
    paddingHorizontal: space.gutter,
    paddingBottom: 8,
  },
  slabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingTop: space.sectionTop,
    paddingHorizontal: space.gutter,
    paddingBottom: 8,
  },
  slabelInline: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansMedium,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.64,
    flex: 1,
  },
  planSectionHint: {
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    paddingHorizontal: space.gutter,
    paddingBottom: 8,
  },
  planEmptyLine: {
    marginHorizontal: space.gutter,
    marginBottom: 10,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.45,
  },
  planEmoji: {
    width: 28,
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
    paddingTop: 1,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  planBack: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: space.gutter,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 8,
  },
  planBackText: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
  },
  planCollectionTitle: {
    fontFamily: fonts.serif,
    fontSize: 26,
    lineHeight: 30,
    color: colors.text,
    paddingHorizontal: space.gutter,
    paddingBottom: 12,
  },
  emptyState: {
    marginHorizontal: space.gutter,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    paddingVertical: 28,
    paddingHorizontal: space.cardPad,
    alignItems: 'center',
  },
  emptyStateText: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: fontSizes.body * 1.5,
  },
  tbox: {
    marginHorizontal: space.gutter,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    paddingVertical: 14,
    paddingHorizontal: space.cardPad,
  },
  tboxTitle: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    color: colors.navy,
    textTransform: 'uppercase',
    letterSpacing: 0.425,
    flex: 1,
  },
  tboxTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 3,
  },
  tboxBody: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.5,
  },
  tboxStrong: {
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  nudge: {
    marginHorizontal: space.gutter,
    marginBottom: space.cardGap,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    padding: space.cardPad,
  },
  nudgeUrgent: {},
  nudgeWatch: {
    backgroundColor: colors.cream,
    borderColor: colors.border,
  },
  nreason: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
    flexShrink: 1,
  },
  nreasonWatch: {
    color: colors.textMuted,
    fontFamily: fonts.sansRegular,
  },
  nudgeDone: {
    opacity: 0.4,
  },
  nudgeSwipeDelete: {
    backgroundColor: colors.terracotta,
    justifyContent: 'center',
    alignItems: 'center',
    width: 84,
    marginBottom: space.cardGap,
    marginRight: space.gutter,
    borderRadius: radii.card,
  },
  nudgeSwipeDeleteText: {
    color: colors.cream,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
  },
  ubadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.blush,
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 5,
    marginBottom: 4,
  },
  ubadgeText: {
    color: colors.navy,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansBold,
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  nsrc: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginBottom: 2,
  },
  nsrcRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 4,
  },
  tayloBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.roseLight,
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  tayloBadgeText: {
    color: colors.roseDark,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansSemiBold,
    letterSpacing: 0.2,
  },
  undoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.roseLight,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  undoBarText: {
    flex: 1,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansRegular,
    color: colors.roseDeep,
    marginRight: 10,
  },
  undoBarBtn: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  nrow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    width: '100%',
    gap: 12,
    alignItems: 'center',
  },
  nicon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  niconText: {
    fontSize: 14,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  ntitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansMedium,
    color: colors.text,
    marginBottom: 3,
    lineHeight: Math.round(fontSizes.title * 1.3),
  },
  ntitleDone: {
    textDecorationLine: 'line-through',
    color: colors.textHint,
  },
  nbody: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
    flexShrink: 1,
  },
  ncopy: {
    flex: 1,
    minWidth: 0,
  },
  nsuggest: {
    marginTop: 0,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
    flex: 1,
  },
  nsuggestRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    marginTop: 8,
  },
  nactions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    flexWrap: 'nowrap',
  },
  prepList: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  prepHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 8,
  },
  prepHeading: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.48,
    flex: 1,
  },
  prepEditBtn: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: colors.paleBlue,
  },
  prepEditBtnText: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  prepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  prepInput: {
    flex: 1,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    borderBottomWidth: 1,
    borderBottomColor: colors.navy,
    paddingVertical: 2,
    margin: 0,
  },
  prepDelete: {
    fontSize: fontSizes.label,
    color: colors.textHint,
    paddingHorizontal: 4,
  },
  prepInlineAdd: {
    marginTop: 8,
    paddingVertical: 4,
  },
  prepInlineAddText: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 18,
  },
  prepInlineAddLink: {
    fontFamily: fonts.sansMedium,
    color: colors.terracotta,
  },
  prepAddText: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  pill: {
    borderRadius: radii.button,
    paddingVertical: 7,
    paddingHorizontal: 12,
    minHeight: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.transparent,
  },
  pillGray: {
    backgroundColor: colors.cream,
    borderColor: colors.navy,
  },
  pillTeal: {
    backgroundColor: colors.terracotta,
  },
  pillDelegate: {
    backgroundColor: colors.cream,
    borderColor: colors.navy,
  },
  pillChat: {
    backgroundColor: colors.cream,
    borderColor: colors.navy,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  pillText: {
    fontSize: fontSizes.label,
    lineHeight: 18,
    fontFamily: fonts.sansMedium,
  },
  pillTextMuted: {
    fontFamily: fonts.sansRegular,
    color: colors.navy,
  },
  pillTextTeal: {
    color: colors.cream,
  },
  pillTextBlue: {
    fontFamily: fonts.sansMedium,
    color: colors.navy,
  },
  pillTextChat: {
    color: colors.navy,
  },
  sorted: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
    color: colors.terracotta,
  },
  uitem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginHorizontal: space.gutter,
    marginBottom: space.cardGap,
    paddingVertical: space.cardPad,
    paddingHorizontal: space.cardPad,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
  },
  planCard: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 0,
    marginHorizontal: space.gutter,
    marginBottom: space.cardGap,
    paddingVertical: space.cardPad,
    paddingHorizontal: space.cardPad,
    backgroundColor: colors.cream,
    borderRadius: radii.card,
    ...cardLift,
  },
  uitemDone: {
    opacity: 0.5,
  },
  udate: {
    width: 30,
    alignItems: 'center',
  },
  uday: {
    fontFamily: fonts.sansSemiBold,
    fontSize: 18,
    color: colors.navy,
    lineHeight: 20,
  },
  umonth: {
    fontSize: fontSizes.micro,
    color: colors.textHint,
    textTransform: 'uppercase',
    fontFamily: fonts.sansSemiBold,
  },
  udiv: {
    width: 1,
    backgroundColor: colors.border,
    alignSelf: 'stretch',
  },
  ubody: {
    flex: 1,
    minWidth: 0,
  },
  uitemHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  uheadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  utitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansMedium,
    color: colors.text,
    marginBottom: 2,
    lineHeight: Math.round(fontSizes.title * 1.25),
  },
  utitleDone: {
    textDecorationLine: 'line-through',
    color: colors.textHint,
  },
  usub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.4,
  },
  uchevron: {
    marginLeft: 'auto',
    fontSize: 11,
    color: colors.textHint,
    flexShrink: 0,
  },
  udetail: {
    marginTop: 7,
    paddingTop: 7,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
  },
  uactions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    flexWrap: 'nowrap',
  },
  clHint: {
    marginHorizontal: space.gutter,
    marginBottom: 6,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.45,
  },
  hcard: {
    marginHorizontal: space.gutter,
    marginBottom: 7,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    overflow: 'hidden',
  },
  hhead: {
    paddingVertical: 8,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  hheadTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
  },
  hheadSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    marginTop: 1,
  },
  clActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginLeft: 'auto',
    flexShrink: 0,
  },
  clIconBtn: {
    width: 22,
    height: 22,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clIconBtnEdit: {
    backgroundColor: colors.paleBlue,
  },
  clIconBtnChat: {
    backgroundColor: colors.paleBlue,
  },
  clIconBtnText: {
    fontSize: fontSizes.title,
  },
  clProg: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 7,
  },
  hitem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  hitemLast: {
    borderBottomWidth: 0,
  },
  hcheck: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hcheckOn: {
    backgroundColor: colors.terracotta,
    borderColor: colors.terracotta,
  },
  hcheckMark: {
    color: colors.white,
    fontSize: 9,
    fontFamily: fonts.sansBold,
    lineHeight: 11,
  },
  htext: {
    flex: 1,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.text,
  },
  htextDone: {
    color: colors.textHint,
    textDecorationLine: 'line-through',
  },
  hwhen: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
  },
  newClBtn: {
    marginTop: 0,
    marginHorizontal: space.gutter,
    marginBottom: 12,
    paddingVertical: 14,
    paddingHorizontal: space.cardPad,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: colors.terracotta,
    borderRadius: radii.card,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  newClIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.terracotta,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newClIconText: {
    fontSize: 13,
    color: colors.white,
    fontFamily: fonts.sansSemiBold,
  },
  newClText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
  },
  newClSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 1,
  },
  addForm: {
    marginHorizontal: space.gutter,
    marginBottom: 12,
    padding: space.cardPad,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.card,
    gap: 8,
  },
  addInput: {
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 12,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    backgroundColor: colors.cream,
  },
  addFormActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  },
  mrow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginHorizontal: space.gutter,
    marginBottom: space.cardGap,
    padding: space.cardPad,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
  },
  mrowIcon: {
    fontSize: 18,
    width: 24,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  mrowTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansMedium,
    color: colors.text,
  },
  mrowSub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  mrowCopy: {
    flex: 1,
    minWidth: 0,
  },
  mrowChevron: {
    marginLeft: 'auto',
    fontSize: 13,
    color: colors.textHint,
  },
  subnav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 11,
    paddingHorizontal: 10,
    paddingBottom: 3,
  },
  subnavBack: {
    fontSize: fontSizes.body,
    color: colors.roseDark,
    fontFamily: fonts.sansSemiBold,
  },
  subnavTitle: {
    fontSize: fontSizes.caption,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.56,
    fontFamily: fonts.sansSemiBold,
  },
  fcard: {
    marginHorizontal: space.gutter,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    overflow: 'hidden',
  },
  fmember: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  fmemberLast: {
    borderBottomWidth: 0,
  },
  favatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  favatarText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
  },
  fname: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  fdetail: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
    lineHeight: fontSizes.body * 1.4,
  },
  ftag: {
    marginLeft: 'auto',
    fontSize: 8,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
  },
  fchevron: {
    fontSize: 10,
    color: colors.textHint,
  },
  connIntro: {
    marginTop: 2,
    marginHorizontal: space.gutter,
    marginBottom: 8,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.5,
  },
  bon: {
    fontSize: 8,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: colors.sage,
    color: colors.navy,
  },
  connSectionLabel: {
    paddingTop: 8,
    paddingHorizontal: 11,
    paddingBottom: 4,
    fontSize: 9,
    fontFamily: fonts.sansSemiBold,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.54,
  },
  connAlso: {
    paddingTop: 4,
    paddingHorizontal: 11,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  connAlsoLabel: {
    fontSize: 9,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginBottom: 5,
  },
  connAlsoBtn: {
    backgroundColor: colors.paleBlue,
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  connAlsoBtnOn: {
    backgroundColor: colors.tealLight,
  },
  connAlsoBtnText: {
    fontSize: 9,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  connAlsoBtnTextOn: {
    color: colors.teal,
    fontFamily: fonts.sansSemiBold,
  },
  pnote: {
    marginVertical: 4,
    marginHorizontal: space.gutter,
    textAlign: 'center',
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.5,
  },
  toggleRow: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.text,
  },
  toggleSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 1,
  },
  watoggle: {
    marginHorizontal: space.gutter,
    marginBottom: 5,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    paddingVertical: 9,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  wlabel: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  wsub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  tswitch: {
    marginLeft: 'auto',
    width: 32,
    height: 18,
    backgroundColor: colors.paleBlue,
    borderRadius: 9,
    justifyContent: 'center',
  },
  tswitchOn: {
    backgroundColor: colors.switchOn,
  },
  tknob: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.white,
    boxShadow: `0px 1px 2px ${colors.knobShadow}`,
    elevation: 2,
  },
  tknobOn: {
    left: 16,
  },
  chatRoot: {
    flex: 1,
    backgroundColor: colors.ivory,
    position: 'relative',
  },
  chatClip: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  chatShift: {
    flex: 1,
    minHeight: 0,
  },
  chatBody: {
    flex: 1,
    minHeight: 0,
  },
  chatSubhead: {
    position: 'relative',
    minHeight: 56,
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: space.gutter,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.cream,
    overflow: 'visible',
  },
  chatLogoCenter: {
    position: 'absolute',
    left: 56,
    right: 56,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.cream,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatIconBtnText: {
    fontSize: 20,
    color: colors.textMuted,
    fontFamily: fonts.sansRegular,
    lineHeight: 22,
  },
  chatThreadAvatar: {
    width: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatThreadAvatarText: {
    fontSize: 11,
    color: colors.navy,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
  },
  chatThreadText: {
    flex: 1,
    minWidth: 0,
  },
  chatThreadTitle: {
    fontSize: fontSizes.header,
    fontFamily: fonts.sansMedium,
    color: colors.text,
  },
  chatThreadSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
  },
  chatMsgs: {
    flexGrow: 1,
    paddingVertical: 14,
    paddingHorizontal: space.gutter,
    gap: 10,
  },
  chatMsgsTap: {
    flexGrow: 1,
    gap: 8,
  },
  bubble: {
    maxWidth: '86%',
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 13,
  },
  bubbleTaylo: {
    backgroundColor: colors.cream,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 3,
    borderWidth: 0,
    borderColor: colors.border,
  },
  bubbleUser: {
    backgroundColor: colors.blush,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 3,
  },
  bubbleText: {
    fontSize: fontSizes.chat,
    fontFamily: fonts.sansRegular,
    lineHeight: fontSizes.chat * 1.45,
  },
  bubbleTextTaylo: {
    color: colors.navy,
  },
  bubbleTextUser: {
    color: colors.navy,
  },
  bsender: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    marginBottom: 2,
    opacity: 0.6,
    textTransform: 'uppercase',
    letterSpacing: 0.32,
    color: colors.navy,
  },
  ecard: {
    marginTop: 6,
    backgroundColor: colors.cream,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ecardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 4,
  },
  ecardTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  ecardFrom: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
  },
  ecardDetail: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
    marginBottom: 5,
  },
  ecardBtns: {
    flexDirection: 'row',
    gap: 4,
  },
  ecardYes: {
    backgroundColor: colors.terracotta,
    borderRadius: 11,
    paddingVertical: 4,
    paddingHorizontal: 9,
  },
  ecardYesText: {
    color: colors.cream,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
  },
  ecardNo: {
    backgroundColor: colors.cream,
    borderRadius: 11,
    paddingVertical: 4,
    paddingHorizontal: 9,
    borderWidth: 1.5,
    borderColor: colors.navy,
  },
  ecardNoText: {
    color: colors.navy,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansRegular,
  },
  chatChips: {
    paddingVertical: 4,
    paddingHorizontal: 9,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    backgroundColor: colors.ivory,
  },
  chatChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: radii.chip,
    borderWidth: 1,
    borderColor: colors.terracotta,
    backgroundColor: colors.cream,
  },
  chatChip: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansRegular,
    color: colors.navy,
  },
  intentPicker: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
    gap: 16,
  },
  intentBubble: {
    width: '100%',
    backgroundColor: colors.cream,
    borderRadius: 28,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  intentBubbleTitle: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.display,
    color: colors.terracotta,
    letterSpacing: -0.4,
  },
  intentBubbleHint: {
    marginTop: 6,
    fontFamily: fonts.sansRegular,
    fontSize: fontSizes.body,
    color: colors.navy,
    opacity: 0.62,
    textAlign: 'center',
  },
  chatBar: {
    paddingVertical: 8,
    paddingHorizontal: 9,
    backgroundColor: colors.cream,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'flex-end',
  },
  chatInput: {
    flex: 1,
    backgroundColor: colors.cream,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: fontSizes.chat,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    maxHeight: 100,
    minHeight: 40,
    lineHeight: fontSizes.chat * 1.35,
  },
  chatRoundBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSend: {
    backgroundColor: colors.terracotta,
  },
  chatMic: {
    backgroundColor: colors.paleBlue,
  },
  typing: {
    backgroundColor: colors.cream,
    borderRadius: 13,
    borderBottomLeftRadius: 3,
    paddingVertical: 9,
    paddingHorizontal: 13,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  tdot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.navy,
  },
  drawer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.drawerScrim,
    zIndex: 15,
    flexDirection: 'row',
  },
  drawerPanel: {
    width: '80%',
    height: '100%',
    backgroundColor: colors.cream,
    boxShadow: `4px 0 12px ${colors.drawerShadow}`,
    elevation: 6,
  },
  cdHeader: {
    paddingTop: 16,
    paddingHorizontal: 12,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  cdTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansBold,
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: 0.63,
  },
  cdClose: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cdCloseText: {
    color: colors.textMuted,
    fontSize: 11,
  },
  cdNew: {
    marginVertical: 8,
    marginHorizontal: 10,
    paddingVertical: 9,
    paddingHorizontal: 10,
    backgroundColor: colors.paleBlue,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cdNewText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  cdItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 8,
    borderRadius: 9,
    marginHorizontal: 6,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.transparent,
  },
  cdItemActive: {
    backgroundColor: colors.paleBlue,
    borderWidth: 1,
    borderColor: colors.terracotta,
  },
  cdItemIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.paleBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cdItemTitle: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  cdItemPreview: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 1,
  },
  cdSwipeDelete: {
    backgroundColor: colors.terracotta,
    justifyContent: 'center',
    alignItems: 'center',
    width: 76,
    marginVertical: 2,
    marginRight: 6,
    borderRadius: 9,
  },
  cdSwipeDeleteText: {
    color: colors.cream,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
  },
  cdEmpty: {
    paddingVertical: 24,
    paddingHorizontal: 16,
    textAlign: 'center',
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.5,
  },
  psHeader: {
    backgroundColor: colors.ivory,
    paddingHorizontal: 14,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  psBack: {
    backgroundColor: colors.cream,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.navy,
  },
  psBackText: {
    color: colors.navy,
    fontSize: 9,
    fontFamily: fonts.sansMedium,
  },
  psAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  psAvatarText: {
    fontSize: 14,
    fontFamily: fonts.sansSemiBold,
  },
  psName: {
    fontSize: 22,
    fontFamily: fonts.serif,
    color: colors.navy,
  },
  psRole: {
    fontSize: 9,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  psEdit: {
    marginLeft: 'auto',
    backgroundColor: colors.cream,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.navy,
  },
  psSection: {
    marginHorizontal: space.gutter,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 0,
    borderColor: colors.border,
    borderRadius: radii.card,
    ...cardLift,
    overflow: 'hidden',
  },
  psSectionTitle: {
    fontSize: 8,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.56,
    paddingTop: 8,
    paddingHorizontal: 11,
    paddingBottom: 4,
  },
  psField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  psFieldLast: {
    borderBottomWidth: 0,
  },
  psFieldCol: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
  },
  psFieldLabel: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  psFieldVal: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.text,
  },
  psFieldEmpty: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    fontStyle: 'italic',
  },
  friendBday: {
    fontSize: 8.5,
    fontFamily: fonts.sansRegular,
    backgroundColor: colors.roseLight,
    color: colors.roseDark,
    paddingVertical: 1,
    paddingHorizontal: 6,
    borderRadius: 5,
    marginTop: 2,
    overflow: 'hidden',
  },
  psAddBtn: {
    marginVertical: 4,
    marginHorizontal: space.gutter,
    paddingVertical: 7,
    paddingHorizontal: 11,
    backgroundColor: colors.paleBlue,
    borderRadius: 9,
    alignItems: 'center',
  },
  psAddBtnText: {
    fontSize: 9.5,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
  },
  homeBrandBar: {
    backgroundColor: colors.ivory,
    paddingHorizontal: space.gutter,
    paddingTop: 4,
    paddingBottom: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeBrandIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  homeBrandIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeGreetBlock: {
    paddingHorizontal: space.gutter,
    paddingTop: 6,
    paddingBottom: 4,
  },
  homeGreetTitle: {
    fontFamily: fonts.serif,
    fontSize: 28,
    lineHeight: 32,
    letterSpacing: -0.3,
    color: colors.navy,
  },
  homeGreetSub: {
    marginTop: 3,
    fontFamily: fonts.sansRegular,
    fontSize: fontSizes.label,
    lineHeight: 20,
    color: colors.textMuted,
  },
  homeSectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: space.gutter,
    paddingTop: 14,
    paddingBottom: 6,
    gap: 8,
  },
  homeSectionLabel: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansBold,
    color: colors.terracotta,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  homeSectionLabelMuted: {
    fontFamily: fonts.sansMedium,
    color: colors.textHint,
  },
  homeSeeAll: {
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansMedium,
    color: colors.terracotta,
  },
  homeSectionHint: {
    paddingHorizontal: space.gutter,
    marginTop: -2,
    marginBottom: 6,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  homeItemTitle: {
    fontSize: fontSizes.card,
    fontFamily: fonts.sansMedium,
    color: colors.text,
    marginBottom: 1,
    lineHeight: 20,
  },
  homeItemSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 17,
  },
  homeExpandDetail: {
    marginTop: 8,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 18,
  },
  homeSuggest: {
    marginTop: 0,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 18,
    flex: 1,
  },
  homeHero: {
    marginHorizontal: space.gutter,
    marginBottom: 2,
    backgroundColor: colors.cream,
    borderRadius: radii.card,
    ...cardLift,
    overflow: 'hidden',
  },
  homeHeroRow: {
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  homeHeroRowLast: {
    borderBottomWidth: 0,
  },
  homeDayCard: {
    marginHorizontal: space.gutter,
    marginTop: 10,
    marginBottom: 8,
    backgroundColor: '#F3F7F9',
    borderRadius: radii.card,
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  homeDayHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
    gap: 12,
  },
  homeDayKicker: {
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansMedium,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  homeDayTitle: {
    marginTop: 2,
    fontFamily: fonts.serif,
    fontSize: 26,
    lineHeight: 30,
    color: colors.navy,
  },
  homeDayCount: {
    marginTop: 3,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  homeDayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  homeDayRailCol: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homeDayRailUp: {
    position: 'absolute',
    top: -16,
    height: 16,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  homeDayRailDown: {
    position: 'absolute',
    top: 36,
    height: 16,
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  homeDayDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: 'rgba(23,43,69,0.28)',
  },
  homeDayTime: {
    width: 62,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansMedium,
    color: colors.navy,
  },
  homeDayName: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
    color: colors.navy,
  },
  homeDaySub: {
    marginTop: 1,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  homeDayFooter: {
    alignSelf: 'flex-end',
    paddingTop: 8,
    paddingBottom: 4,
  },
  homeDayFooterText: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansMedium,
    color: colors.terracotta,
  },
  homeNoticed: {
    marginHorizontal: space.gutter,
    marginBottom: 2,
    backgroundColor: colors.blush,
    borderRadius: radii.card,
    paddingVertical: 18,
    paddingHorizontal: 18,
  },
  homeNoticedHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  homeNoticedLabel: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansMedium,
    color: colors.terracotta,
    textTransform: 'uppercase',
    letterSpacing: 0.72,
  },
  homeNoticedText: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.navy,
    lineHeight: 23,
  },
  homeFamilyScroll: {
    flexGrow: 0,
  },
  homeFamilyRow: {
    paddingLeft: space.gutter,
    paddingRight: space.gutter,
    paddingBottom: 2,
    gap: 8,
    alignItems: 'stretch',
  },
  homeFamilyCard: {
    width: 148,
    minHeight: 168,
    backgroundColor: colors.cream,
    borderRadius: radii.card,
    paddingVertical: 14,
    paddingHorizontal: 12,
    ...cardLift,
    alignItems: 'flex-start',
    flexShrink: 0,
    overflow: 'hidden',
  },
  homeFamilyAvatar: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    alignSelf: 'center',
  },
  homeFamilyPhoto: {
    width: '100%',
    height: '100%',
  },
  homeFamilyInitial: {
    fontSize: 18,
    lineHeight: 22,
    fontFamily: fonts.sansMedium,
    color: colors.navy,
    textAlign: 'center',
    includeFontPadding: false,
  },
  homeFamilyName: {
    marginTop: 10,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.navy,
    textAlign: 'left',
    width: '100%',
  },
  homeFamilyDoing: {
    marginTop: 8,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    width: '100%',
    flex: 1,
  },
  homeFamilyItem: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.navy,
    textAlign: 'left',
    lineHeight: 17,
  },
  homeFamilyWhen: {
    marginTop: 2,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 15,
  },
  homeReassure: {
    marginHorizontal: space.gutter,
    marginTop: 10,
    marginBottom: 8,
    backgroundColor: colors.sage,
    borderRadius: radii.card,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  homeReassureCopy: {
    flex: 1,
    minWidth: 0,
  },
  homeReassureTitle: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
    color: colors.navy,
  },
  homeReassureSub: {
    marginTop: 2,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: 16,
  },
});
