import { colors, fonts, fontSizes } from '@/constants/theme';
import { StyleSheet } from 'react-native';

export const iconBg = {
  rose: colors.roseLight,
  amber: colors.amberLight,
  teal: colors.tealLight,
  blue: colors.blueLight,
  purple: colors.purpleLight,
  green: colors.greenLight,
};

export const appStyles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: colors.grayLight,
  },
  headerWrap: {
    backgroundColor: colors.rose,
  },
  header: {
    backgroundColor: colors.rose,
    paddingHorizontal: 14,
    paddingTop: 2,
    overflow: 'hidden',
  },
  greeting: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansLight,
    color: colors.white,
    opacity: 0.8,
    marginBottom: 1,
  },
  appName: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.display,
    letterSpacing: -0.5,
    color: colors.white,
  },
  mlBar: {
    backgroundColor: colors.headerPill,
    marginTop: 5,
    marginBottom: 8,
    borderRadius: 7,
    paddingVertical: 6,
    paddingHorizontal: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mlStat: {
    fontSize: fontSizes.label,
    color: colors.headerStat,
    fontFamily: fonts.sansMedium,
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: colors.cream,
    borderTopWidth: 1.5,
    borderTopColor: colors.border,
    boxShadow: `0px -3px 16px ${colors.tabShadow}`,
    elevation: 8,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 11,
    paddingBottom: 4,
    borderTopWidth: 2.5,
    borderTopColor: colors.transparent,
  },
  tabActive: {
    borderTopColor: colors.roseDark,
  },
  tabLabel: {
    marginTop: 4,
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    letterSpacing: 0.085,
  },
  tabLabelActive: {
    color: colors.roseDark,
  },
  screen: {
    flexGrow: 1,
    backgroundColor: colors.grayLight,
    paddingBottom: 8,
  },
  slabel: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.64,
    paddingTop: 9,
    paddingHorizontal: 10,
    paddingBottom: 2,
  },
  planSectionHint: {
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    paddingHorizontal: 10,
    paddingBottom: 6,
  },
  planEmptyLine: {
    marginHorizontal: 10,
    marginBottom: 10,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.45,
  },
  planEmoji: {
    width: 28,
    fontSize: 18,
    lineHeight: 22,
    textAlign: 'center',
    paddingTop: 1,
  },
  planBack: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 4,
    gap: 6,
  },
  planBackText: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
  },
  planCollectionTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
    paddingHorizontal: 10,
    paddingBottom: 8,
  },
  emptyState: {
    marginHorizontal: 7,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingVertical: 22,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  emptyStateText: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    textAlign: 'center',
    lineHeight: fontSizes.body * 1.5,
  },
  tbox: {
    marginHorizontal: 7,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 9,
    paddingHorizontal: 10,
  },
  tboxTitle: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
    textTransform: 'uppercase',
    letterSpacing: 0.425,
    marginBottom: 3,
  },
  tboxBody: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.5,
  },
  tboxStrong: {
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  nudge: {
    marginHorizontal: 7,
    marginBottom: 7,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 10,
  },
  nudgeUrgent: {
    borderColor: colors.rose,
    borderWidth: 1.5,
  },
  nudgeWatch: {
    backgroundColor: colors.grayLight,
    borderColor: 'transparent',
  },
  nreason: {
    fontSize: fontSizes.card,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
    lineHeight: fontSizes.card * 1.4,
    flexShrink: 1,
  },
  nreasonWatch: {
    color: colors.textMuted,
    fontFamily: fonts.sansRegular,
  },
  nudgeDone: {
    opacity: 0.4,
  },
  nudgeSwipeDelete: {
    backgroundColor: colors.rose,
    justifyContent: 'center',
    alignItems: 'center',
    width: 84,
    marginBottom: 7,
    marginRight: 7,
    borderRadius: 12,
  },
  nudgeSwipeDeleteText: {
    color: colors.white,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
  },
  ubadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.rose,
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 5,
    marginBottom: 4,
  },
  ubadgeText: {
    color: colors.white,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansBold,
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  nsrc: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginBottom: 4,
  },
  nsrcRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 4,
  },
  tayloBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.roseLight,
    borderRadius: 4,
    paddingVertical: 2,
    paddingHorizontal: 6,
  },
  tayloBadgeText: {
    color: colors.roseDark,
    fontSize: fontSizes.micro,
    fontFamily: fonts.sansSemiBold,
    letterSpacing: 0.2,
  },
  undoBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.roseLight,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  undoBarText: {
    flex: 1,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansRegular,
    color: colors.roseDeep,
    marginRight: 10,
  },
  undoBarBtn: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  nrow: {
    flexDirection: 'row',
    gap: 7,
    alignItems: 'flex-start',
  },
  nicon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  niconText: {
    fontSize: 14,
  },
  ntitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
    marginBottom: 2,
  },
  ntitleDone: {
    textDecorationLine: 'line-through',
    color: colors.textHint,
  },
  nbody: {
    fontSize: fontSizes.card,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.card * 1.45,
    flexShrink: 1,
  },
  ncopy: {
    flex: 1,
    minWidth: 0,
  },
  nsuggest: {
    marginTop: 8,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
    lineHeight: fontSizes.body * 1.4,
  },
  nactions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    flexWrap: 'nowrap',
  },
  prepList: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  prepHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    gap: 8,
  },
  prepHeading: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.48,
    flex: 1,
  },
  prepEditBtn: {
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: colors.grayLight,
  },
  prepEditBtnText: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  prepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 5,
  },
  prepInput: {
    flex: 1,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    borderBottomWidth: 1,
    borderBottomColor: colors.rose,
    paddingVertical: 2,
    margin: 0,
  },
  prepDelete: {
    fontSize: fontSizes.label,
    color: colors.textHint,
    paddingHorizontal: 4,
  },
  prepAdd: {
    paddingVertical: 8,
  },
  prepAddText: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  pill: {
    borderRadius: 20,
    paddingVertical: 7,
    paddingHorizontal: 12,
    minHeight: 34,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: colors.transparent,
  },
  pillGray: {
    backgroundColor: colors.grayLight,
  },
  pillTeal: {
    backgroundColor: colors.tealLight,
  },
  pillDelegate: {
    backgroundColor: colors.blueLight,
  },
  pillChat: {
    backgroundColor: colors.cream,
    borderColor: colors.rose,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  pillText: {
    fontSize: fontSizes.label,
    lineHeight: 18,
    fontFamily: fonts.sansSemiBold,
  },
  pillTextMuted: {
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  pillTextTeal: {
    color: colors.teal,
  },
  pillTextBlue: {
    fontFamily: fonts.sansMedium,
    color: colors.blue,
  },
  pillTextChat: {
    color: colors.roseDark,
  },
  sorted: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansMedium,
    color: colors.teal,
  },
  uitem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginHorizontal: 7,
    marginBottom: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 9,
  },
  uitemDone: {
    opacity: 0.5,
  },
  udate: {
    width: 30,
    alignItems: 'center',
  },
  uday: {
    fontFamily: fonts.serif,
    fontSize: 17,
    color: colors.roseDark,
    lineHeight: 17,
  },
  umonth: {
    fontSize: fontSizes.micro,
    color: colors.textHint,
    textTransform: 'uppercase',
    fontFamily: fonts.sansSemiBold,
  },
  udiv: {
    width: 1,
    backgroundColor: colors.border,
    alignSelf: 'stretch',
  },
  ubody: {
    flex: 1,
    minWidth: 0,
  },
  uheadRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
  },
  utitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
    marginBottom: 1,
  },
  utitleDone: {
    textDecorationLine: 'line-through',
    color: colors.textHint,
  },
  usub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.4,
  },
  uchevron: {
    marginLeft: 'auto',
    fontSize: 11,
    color: colors.textHint,
    paddingTop: 1,
  },
  udetail: {
    marginTop: 7,
    paddingTop: 7,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
  },
  uactions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    flexWrap: 'nowrap',
  },
  clHint: {
    marginHorizontal: 7,
    marginBottom: 6,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.45,
  },
  hcard: {
    marginHorizontal: 7,
    marginBottom: 7,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    overflow: 'hidden',
  },
  hhead: {
    paddingVertical: 8,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  hheadTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
  },
  hheadSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    marginTop: 1,
  },
  clActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginLeft: 'auto',
    flexShrink: 0,
  },
  clIconBtn: {
    width: 22,
    height: 22,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  clIconBtnEdit: {
    backgroundColor: colors.grayLight,
  },
  clIconBtnChat: {
    backgroundColor: colors.roseLight,
  },
  clIconBtnText: {
    fontSize: fontSizes.title,
  },
  clProg: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 7,
  },
  hitem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  hitemLast: {
    borderBottomWidth: 0,
  },
  hcheck: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hcheckOn: {
    backgroundColor: colors.teal,
    borderColor: colors.teal,
  },
  hcheckMark: {
    color: colors.white,
    fontSize: 9,
    fontFamily: fonts.sansBold,
    lineHeight: 11,
  },
  htext: {
    flex: 1,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
  },
  htextDone: {
    color: colors.textHint,
    textDecorationLine: 'line-through',
  },
  hwhen: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
  },
  newClBtn: {
    marginTop: 5,
    marginHorizontal: 7,
    marginBottom: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    backgroundColor: colors.cream,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.rose,
    borderRadius: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  newClIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.rose,
    alignItems: 'center',
    justifyContent: 'center',
  },
  newClIconText: {
    fontSize: 13,
    color: colors.white,
    fontFamily: fonts.sansSemiBold,
  },
  newClText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
  },
  newClSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 1,
  },
  addForm: {
    marginHorizontal: 7,
    marginBottom: 12,
    padding: 12,
    backgroundColor: colors.cream,
    borderWidth: 1.5,
    borderColor: colors.rose,
    borderRadius: 11,
    gap: 8,
  },
  addInput: {
    borderWidth: 1.5,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 11,
    paddingHorizontal: 12,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    backgroundColor: colors.white,
  },
  addFormActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 4,
  },
  mrow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    marginHorizontal: 7,
    marginBottom: 6,
    padding: 11,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
  },
  mrowIcon: {
    fontSize: 18,
    width: 24,
    textAlign: 'center',
  },
  mrowTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  mrowSub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  mrowCopy: {
    flex: 1,
    minWidth: 0,
  },
  mrowChevron: {
    marginLeft: 'auto',
    fontSize: 13,
    color: colors.textHint,
  },
  subnav: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 11,
    paddingHorizontal: 10,
    paddingBottom: 3,
  },
  subnavBack: {
    fontSize: fontSizes.body,
    color: colors.roseDark,
    fontFamily: fonts.sansSemiBold,
  },
  subnavTitle: {
    fontSize: fontSizes.caption,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.56,
    fontFamily: fonts.sansSemiBold,
  },
  fcard: {
    marginHorizontal: 7,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    overflow: 'hidden',
  },
  fmember: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  fmemberLast: {
    borderBottomWidth: 0,
  },
  favatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  favatarText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
  },
  fname: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  fdetail: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
    lineHeight: fontSizes.body * 1.4,
  },
  ftag: {
    marginLeft: 'auto',
    fontSize: 8,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
  },
  fchevron: {
    fontSize: 10,
    color: colors.textHint,
  },
  connIntro: {
    marginTop: 2,
    marginHorizontal: 7,
    marginBottom: 8,
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.5,
  },
  bon: {
    fontSize: 8,
    fontFamily: fonts.sansSemiBold,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 6,
    backgroundColor: colors.tealLight,
    color: colors.teal,
  },
  connSectionLabel: {
    paddingTop: 8,
    paddingHorizontal: 11,
    paddingBottom: 4,
    fontSize: 9,
    fontFamily: fonts.sansSemiBold,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.54,
  },
  connAlso: {
    paddingTop: 4,
    paddingHorizontal: 11,
    paddingBottom: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  connAlsoLabel: {
    fontSize: 9,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginBottom: 5,
  },
  connAlsoBtn: {
    backgroundColor: colors.grayLight,
    borderRadius: 8,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  connAlsoBtnOn: {
    backgroundColor: colors.tealLight,
  },
  connAlsoBtnText: {
    fontSize: 9,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  connAlsoBtnTextOn: {
    color: colors.teal,
    fontFamily: fonts.sansSemiBold,
  },
  pnote: {
    marginVertical: 4,
    marginHorizontal: 7,
    textAlign: 'center',
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.5,
  },
  toggleRow: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.text,
  },
  toggleSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 1,
  },
  watoggle: {
    marginHorizontal: 7,
    marginBottom: 5,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    paddingVertical: 9,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  wlabel: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  wsub: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    marginTop: 1,
  },
  tswitch: {
    marginLeft: 'auto',
    width: 32,
    height: 18,
    backgroundColor: colors.grayLight,
    borderRadius: 9,
    justifyContent: 'center',
  },
  tswitchOn: {
    backgroundColor: colors.switchOn,
  },
  tknob: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: colors.white,
    boxShadow: `0px 1px 2px ${colors.knobShadow}`,
    elevation: 2,
  },
  tknobOn: {
    left: 16,
  },
  chatRoot: {
    flex: 1,
    backgroundColor: colors.grayLight,
    position: 'relative',
  },
  chatClip: {
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  chatShift: {
    flex: 1,
    minHeight: 0,
  },
  chatBody: {
    flex: 1,
    minHeight: 0,
  },
  chatSubhead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.cream,
  },
  chatIconBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.grayLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatIconBtnText: {
    fontSize: 20,
    color: colors.textMuted,
    fontFamily: fonts.sansRegular,
    lineHeight: 22,
  },
  chatThreadAvatar: {
    width: 23,
    height: 23,
    borderRadius: 12,
    backgroundColor: colors.roseLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatThreadAvatarText: {
    fontSize: 11,
    color: colors.roseDark,
    fontFamily: fonts.sansSemiBold,
  },
  chatThreadText: {
    flex: 1,
    minWidth: 0,
  },
  chatThreadTitle: {
    fontSize: fontSizes.header,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  chatThreadSub: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
  },
  chatMsgs: {
    flexGrow: 1,
    paddingVertical: 9,
    paddingHorizontal: 9,
    gap: 8,
  },
  chatMsgsTap: {
    flexGrow: 1,
    gap: 8,
  },
  bubble: {
    maxWidth: '86%',
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 13,
  },
  bubbleTaylo: {
    backgroundColor: colors.roseLight,
    alignSelf: 'flex-start',
    borderBottomLeftRadius: 3,
  },
  bubbleUser: {
    backgroundColor: colors.rose,
    alignSelf: 'flex-end',
    borderBottomRightRadius: 3,
  },
  bubbleText: {
    fontSize: fontSizes.chat,
    fontFamily: fonts.sansRegular,
    lineHeight: fontSizes.chat * 1.45,
  },
  bubbleTextTaylo: {
    color: colors.roseDeep,
  },
  bubbleTextUser: {
    color: colors.white,
  },
  bsender: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansSemiBold,
    marginBottom: 2,
    opacity: 0.6,
    textTransform: 'uppercase',
    letterSpacing: 0.32,
    color: colors.roseDeep,
  },
  ecard: {
    marginTop: 6,
    backgroundColor: colors.cream,
    borderRadius: 8,
    paddingVertical: 7,
    paddingHorizontal: 9,
    borderWidth: 1,
    borderColor: colors.border,
  },
  ecardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 4,
  },
  ecardTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  ecardFrom: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
  },
  ecardDetail: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
    lineHeight: fontSizes.body * 1.45,
    marginBottom: 5,
  },
  ecardBtns: {
    flexDirection: 'row',
    gap: 4,
  },
  ecardYes: {
    backgroundColor: colors.teal,
    borderRadius: 11,
    paddingVertical: 4,
    paddingHorizontal: 9,
  },
  ecardYesText: {
    color: colors.white,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
  },
  ecardNo: {
    backgroundColor: colors.grayLight,
    borderRadius: 11,
    paddingVertical: 4,
    paddingHorizontal: 9,
  },
  ecardNoText: {
    color: colors.textMuted,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansRegular,
  },
  chatChips: {
    paddingVertical: 4,
    paddingHorizontal: 9,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    backgroundColor: colors.grayLight,
  },
  chatChip: {
    fontSize: fontSizes.label,
    fontFamily: fonts.sansRegular,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.rose,
    color: colors.roseDark,
    backgroundColor: colors.cream,
    overflow: 'hidden',
  },
  intentPicker: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 28,
    gap: 16,
  },
  intentBubble: {
    width: '100%',
    backgroundColor: colors.rose,
    borderRadius: 28,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
    boxShadow: `0px 8px 24px ${colors.tabShadow}`,
    elevation: 4,
  },
  intentBubbleTitle: {
    fontFamily: fonts.serif,
    fontSize: fontSizes.display,
    color: colors.white,
    letterSpacing: -0.4,
  },
  intentBubbleHint: {
    marginTop: 6,
    fontFamily: fonts.sansRegular,
    fontSize: fontSizes.body,
    color: colors.white,
    opacity: 0.72,
    textAlign: 'center',
  },
  chatBar: {
    paddingVertical: 8,
    paddingHorizontal: 9,
    backgroundColor: colors.cream,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'flex-end',
  },
  chatInput: {
    flex: 1,
    backgroundColor: colors.grayLight,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 12,
    fontSize: fontSizes.chat,
    fontFamily: fonts.sansRegular,
    color: colors.text,
    maxHeight: 100,
    minHeight: 40,
    lineHeight: fontSizes.chat * 1.35,
  },
  chatRoundBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatSend: {
    backgroundColor: colors.rose,
  },
  chatMic: {
    backgroundColor: colors.grayLight,
  },
  typing: {
    backgroundColor: colors.roseLight,
    borderRadius: 13,
    borderBottomLeftRadius: 3,
    paddingVertical: 9,
    paddingHorizontal: 13,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    alignItems: 'center',
  },
  tdot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.rose,
  },
  drawer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.drawerScrim,
    zIndex: 15,
    flexDirection: 'row',
  },
  drawerPanel: {
    width: '80%',
    height: '100%',
    backgroundColor: colors.cream,
    boxShadow: `6px 0 24px ${colors.drawerShadow}`,
    elevation: 12,
  },
  cdHeader: {
    paddingTop: 16,
    paddingHorizontal: 12,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  cdTitle: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansBold,
    color: colors.text,
    textTransform: 'uppercase',
    letterSpacing: 0.63,
  },
  cdClose: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.grayLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cdCloseText: {
    color: colors.textMuted,
    fontSize: 11,
  },
  cdNew: {
    marginVertical: 8,
    marginHorizontal: 10,
    paddingVertical: 9,
    paddingHorizontal: 10,
    backgroundColor: colors.roseLight,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cdNewText: {
    fontSize: fontSizes.title,
    fontFamily: fonts.sansSemiBold,
    color: colors.roseDark,
  },
  cdItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 8,
    borderRadius: 9,
    marginHorizontal: 6,
    backgroundColor: colors.cream,
  },
  cdItemActive: {
    backgroundColor: colors.roseLight,
  },
  cdItemIcon: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.grayLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cdItemTitle: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansSemiBold,
    color: colors.text,
  },
  cdItemPreview: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    marginTop: 1,
  },
  cdSwipeDelete: {
    backgroundColor: colors.rose,
    justifyContent: 'center',
    alignItems: 'center',
    width: 76,
    marginVertical: 2,
    marginRight: 6,
    borderRadius: 9,
  },
  cdSwipeDeleteText: {
    color: colors.white,
    fontSize: fontSizes.label,
    fontFamily: fonts.sansSemiBold,
  },
  cdEmpty: {
    paddingVertical: 24,
    paddingHorizontal: 16,
    textAlign: 'center',
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    lineHeight: fontSizes.body * 1.5,
  },
  psHeader: {
    backgroundColor: colors.rose,
    paddingHorizontal: 14,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  psBack: {
    backgroundColor: colors.whiteMuted,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  psBackText: {
    color: colors.white,
    fontSize: 9,
    fontFamily: fonts.sansMedium,
  },
  psAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  psAvatarText: {
    fontSize: 14,
    fontFamily: fonts.sansSemiBold,
  },
  psName: {
    fontSize: 14,
    fontFamily: fonts.serif,
    color: colors.white,
  },
  psRole: {
    fontSize: 9,
    fontFamily: fonts.sansRegular,
    color: 'rgba(255,255,255,0.75)',
    marginTop: 1,
  },
  psEdit: {
    marginLeft: 'auto',
    backgroundColor: colors.whiteMuted,
    borderRadius: 10,
    paddingVertical: 4,
    paddingHorizontal: 10,
  },
  psSection: {
    marginHorizontal: 7,
    marginBottom: 8,
    backgroundColor: colors.cream,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 11,
    overflow: 'hidden',
  },
  psSectionTitle: {
    fontSize: 8,
    fontFamily: fonts.sansSemiBold,
    color: colors.textHint,
    textTransform: 'uppercase',
    letterSpacing: 0.56,
    paddingTop: 8,
    paddingHorizontal: 11,
    paddingBottom: 4,
  },
  psField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
    paddingHorizontal: 11,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  psFieldLast: {
    borderBottomWidth: 0,
  },
  psFieldCol: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
  },
  psFieldLabel: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textMuted,
  },
  psFieldVal: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansMedium,
    color: colors.text,
  },
  psFieldEmpty: {
    fontSize: fontSizes.body,
    fontFamily: fonts.sansRegular,
    color: colors.textHint,
    fontStyle: 'italic',
  },
  friendBday: {
    fontSize: 8.5,
    fontFamily: fonts.sansRegular,
    backgroundColor: colors.roseLight,
    color: colors.roseDark,
    paddingVertical: 1,
    paddingHorizontal: 6,
    borderRadius: 5,
    marginTop: 2,
    overflow: 'hidden',
  },
  psAddBtn: {
    marginVertical: 4,
    marginHorizontal: 7,
    paddingVertical: 7,
    paddingHorizontal: 11,
    backgroundColor: colors.grayLight,
    borderRadius: 9,
    alignItems: 'center',
  },
  psAddBtnText: {
    fontSize: 9.5,
    fontFamily: fonts.sansMedium,
    color: colors.roseDark,
  },
});
